language:
  - c

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - COVERAGE=ON
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: clang-3.6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
          packages:
            - clang-3.6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: clang
      before_install:
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
          packages:
            - clang-3.6
            - libpython3.5-dev
            - cython3
            - python3-numpy

      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-4.4
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.4
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-4.7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.7
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-4.8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libpython2.7
            - cython
            - python-numpy
      env:
        - PYTHON_VERSION=2.7

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython2.7
            - cython
            - python-numpy
      env:
        - PYTHON_VERSION=2.7

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - C_STANDARD=90
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - C_STANDARD=11
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5-dev
            - cython3
            - python3-numpy
      env:
        - CXX_STANDARD=11
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5
            - cython3
            - python3-numpy
      env:
        - CXX_STANDARD=14
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libpython3.5
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: linux
      dist: xenial
      compiler: gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - libpython3.5
            - cython3
            - python3-numpy
      env:
        - PYTHON_VERSION=3.5

    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env:
        - PYTHON_VERSION=3.5

    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      env:
        - PYTHON_VERSION=2.7

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - PYTHON_VERSION=3.5

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - PYTHON_VERSION=2.7

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv root; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "2.7" ]; then pyenv install 2.7.12; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "3.5" ]; then pyenv install 3.5.0; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "2.7" ]; then export PYTHON_INCLUDE_DIR=$(pyenv root)/versions/2.7.12/include/python2.7; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "2.7" ]; then export PYTHON_LIBRARY=$(pyenv root)/versions/2.7.12/lib/libpython2.7.dylib; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "2.7" ]; then export PYTHON_BINARY=$(pyenv root)/versions/2.7.12/bin/python2.7; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "3.5" ]; then export PYTHON_INCLUDE_DIR=$(pyenv root)/versions/3.5.0/include/python3.5m; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "3.5" ]; then export PYTHON_LIBRARY=$(pyenv root)/versions/3.5.0/lib/libpython3.dylib; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "3.5" ]; then export PYTHON_BINARY=$(pyenv root)/versions/3.5.0/bin/python3.5; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then $PYTHON_BINARY -m pip install --upgrade pip; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then $PYTHON_BINARY -m pip install Cython; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then $PYTHON_BINARY -m pip install numpy; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then $PYTHON_BINARY -m pip install six; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PYTHON_BINARY=/usr/bin/python$PYTHON_VERSION; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PYTHON_VERSION" = "2.7" ]; then export PYTHON_INCLUDE_DIR=/usr/include/python2.7; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PYTHON_VERSION" = "2.7" ]; then export PYTHON_LIBRARY=/usr/lib/libpython2.7.so; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PYTHON_VERSION" = "3.5" ]; then export PYTHON_INCLUDE_DIR=/usr/include/python3.5m; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PYTHON_VERSION" = "3.5" ]; then export PYTHON_LIBRARY=/usr/lib/libpython3.5m.so; fi

  - ./travis.sh

after_success:
  - if [[ -n "${COVERAGE}" ]]; then bash <(curl -s https://codecov.io/bash); fi
